# Generated by Django 3.1.7 on 2021-02-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_project_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='receiver',
            new_name='done_by',
        ),
    ]
